### ISSUE TITLE
Line 1 class/style ignored

### ISSUE THREAD

**Issue by haikbaba** [purifycss/purifycss#69] opened 2015-06-28 22:10 UTC
I've discovered that the 1st class/style is not included in the output. This only occurs if Line 1 in the CSS file is a class. 

My command from within VS2013 PM Console...
PM> purifycss "E:\WebApplication\Content\bootstrap.css","E:\WebApplication\Content\Site.css" "E:\WebApplication\Views\Home\_Home.cshtml","E:\WebApplication\Views\Shared\_Layout.cshtml","E:\WebApplication\Views\Shared\_LoginPartial.cshtml","E:\WebApplication\Views\Account\Login.cshtml" --min --out "E:\WebApplication\Content\PURIFIED.css"

Ignored in the output was Line 1 in my Site.css which contained a "body{}" with additional parameters (not overrides).
The workaround is making that Line 1 a comment and having CSS begin below that.

**Comment by kennyt** [comment] 2015-06-29 03:52
I can't seem to reproduce this. Can you please show me the troublesome line #1?

Also, I'm just going off a hunch here, can you show me the last line of your ```bootstrap.css```?

**Comment by haikbaba** [comment] 2015-06-29 09:23
Sure thing, here you go...


              
              


Date: Sun, 28 Jun 2015 20:52:36 -0700

**Comment by kennyt** [comment] 2015-07-31 20:53
Cannot reproduce. Going to close this.

**Closed by kennyt** 2015-07-31 20:53 UTC
